-- Test agent account (password: test123)
-- bcrypt hash generated by Spring Security BCryptPasswordEncoder
INSERT INTO users (email, password_hash, display_name, role, status) VALUES
('agent@test.com', '$2a$10$4R2YkfMT6xtdFPgbwMK11u7VhoRTbGDyUkPzdPMIKdILSzRqvV.aS', 'Test Agent', 'AGENT', 'OFFLINE'),
('admin@test.com', '$2a$10$4R2YkfMT6xtdFPgbwMK11u7VhoRTbGDyUkPzdPMIKdILSzRqvV.aS', 'Test Admin', 'ADMIN', 'OFFLINE');

-- Sample canned responses
INSERT INTO canned_responses (shortcut, content, created_by) VALUES
('/hello', 'Hello! How can I help you today?', 1),
('/thanks', 'Thank you for contacting us! Is there anything else I can help with?', 1),
('/wait', 'Please wait a moment while I look into this for you.', 1),
('/bye', 'Thank you for chatting with us. Have a great day!', 1);
